spring:
  datasource:
          url: jdbc:mysql://47.94.225.151:3306/dev?useUnicode=true&characterEncoding=UTF-8&useSSL=false
          username: ylin
          password: ylinylin
          driver-class-name: com.mysql.cj.jdbc.Driver
  profiles: dev
  jpa:
    show-sql: true
