spring:
  profiles:
    active: @spring.profiles.active@
  redis:
    database: 0
    host: localhost
    password:
mybatis:
  type-aliases-package: pers.ylin.demo.entity
  mapper-locations: classpath:mapper/*.xml
server:
  port: 9000